name: Build release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v .
      
    - name: Make release
      uses: softprops/action-gh-release@v0.1.5
      with:
        files: winter-polaris-webvtt.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
